image: docker:stable

stages:
  - build
  - test
  - package

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

Default:
  stage: package
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f Dockerfile --build-arg SERVER_VERSION=1.14.4 .
    - docker push $IMAGE_TAG
    - docker rmi $IMAGE_TAG
  tags: ["docker"]
  only:
    - master

Vanilla_1.14.3:
  stage: package
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:vanilla-1.14.3
    LATEST_TAG: $CI_REGISTRY_IMAGE:vanilla
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f Dockerfile.vanilla --build-arg SERVER_VERSION=1.14.4 .
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG
    - docker rmi $IMAGE_TAG $LATEST_TAG
  tags: ["docker"]
  only:
    - master

Spigot_1.14.3:
  stage: package
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:spigot-1.14.3
    LATEST_TAG: $CI_REGISTRY_IMAGE:spigot
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f Dockerfile.spigot --build-arg SERVER_VERSION=1.14.4 .
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG
    - docker rmi $IMAGE_TAG $LATEST_TAG
  tags: ["docker"]
  only:
    - master
